name: SCHINDHELM
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23231
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#bdb296'
    - '#808483'
    - '#181c1f'
    - '#4c4e4d'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
